version: "3.9"

services:
  # --------------------------
  # MYSQL DATABASE
  # --------------------------
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # --------------------------
  # EUREKA SERVICE REGISTRY
  # --------------------------
  service-registry:
    build:
      context: ./Backend/ServiceRegistry
      dockerfile: Dockerfile
    container_name: service-registry
    ports:
      - "8761:8761"
    depends_on:
      - mysql

  # --------------------------
  # API GATEWAY
  # --------------------------
  api-gateway:
    build:
      context: ./Backend/APIGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "9090:9090"
    depends_on:
      - service-registry

  # --------------------------
  # MICRO SERVICES (EXAMPLES)
  # --------------------------

  admin-login:
    build:
      context: ./Backend/AdminLogin
      dockerfile: Dockerfile
    container_name: admin-login
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/superadmin_log_admin_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      - mysql
      - service-registry

  admin-meal:
    build:
      context: ./Backend/AdminMeal
      dockerfile: Dockerfile
    container_name: admin-meal
    depends_on:
      - mysql
      - service-registry

  user-auth:
    build:
      context: ./Backend/UserAuth
      dockerfile: Dockerfile
    container_name: user-auth
    depends_on:
      - mysql
      - service-registry

  user-menu:
    build:
      context: ./Backend/UserMenu
      dockerfile: Dockerfile
    container_name: user-menu
    depends_on:
      - mysql
      - service-registry

  cart-service:
    build:
      context: ./Backend/CartService
      dockerfile: Dockerfile
    container_name: cart-service
    depends_on:
      - mysql
      - service-registry

  admin-subscription:
    build:
      context: ./Backend/AdminSubscription
      dockerfile: Dockerfile
    container_name: admin-subscription
    depends_on:
      - mysql
      - service-registry

  user-subscription:
    build:
      context: ./Backend/UserSubscription
      dockerfile: Dockerfile
    container_name: user-subscription
    depends_on:
      - mysql
      - service-registry

  admin-order:
    build:
      context: ./Backend/AdminOrder
      dockerfile: Dockerfile
    container_name: admin-order
    depends_on:
      - mysql
      - service-registry

  user-order:
    build:
      context: ./Backend/UserOrder
      dockerfile: Dockerfile
    container_name: user-order
    depends_on:
      - mysql
      - service-registry

  admin-review:
    build:
      context: ./Backend/AdminReview
      dockerfile: Dockerfile
    container_name: admin-review
    depends_on:
      - mysql
      - service-registry

  user-review:
    build:
      context: ./Backend/UserReview
      dockerfile: Dockerfile
    container_name: user-review
    depends_on:
      - mysql
      - service-registry

  # --------------------------
  # FRONTEND
  # --------------------------
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: tiffino-frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway

volumes:
  mysql-data:
